version: "3"

services:
  reverse-proxy:
    image: traefik:2.3
    restart: always
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.watch=true"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
    - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.websecure.http.tls=true"
    - "--entrypoints.websecure.http.tls.certresolver=myresolver"
    - "--certificatesresolvers.myresolver.acme.email=julian.baehr@googlemail.com"
    - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
    - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=route53"
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    networks:
    - "traefik"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik:
    external: true