---
# file: roles/dockerserver/tasks/install_docker.yml

- name: install ansible requirement docker
  pip:
    name: docker

- name: install ansible requirements docker-compose
  pip:
    name: docker-compose~=1.23.0

- name: check if docker is installed
  stat:
    path: /etc/flags/docker-installed
  register: docker_installed_result

- name: install docker
  shell: "sudo amazon-linux-extras install docker -y"
  when: not docker_installed_result.stat.exists

- name: set docker exists flag file
  copy:
    content: ""
    dest: /etc/flags/docker-installed
    force: no
    group: sys
    owner: root
    mode: 0555
  when: not docker_installed_result.stat.exists

- name: auto start docker service
  systemd:
    state: started
    enabled: yes
    name: docker

- name: create daemon json
  copy:
    dest: /etc/docker/daemon.json
    src: files/daemon.json
  notify: restart docker